Template 01 list created
OntimizeWeb/ontimize-web-templates pull request #12
Opened 2024-07-02 13:08 UTC by javier-fernandez-imatia

2024-07-03 05:01 UTC, patricia-martinez-imatia requested changes

2024-07-03 05:01 UTC, patricia-martinez-imatia commented on templates/list/01-list/README.md
> +<li>Download and put `list` folder in src/app/ and `i18n` into assets/  </li>
El markdown en el li no se renderiza, ya lo comente en mas ocasiones

2024-07-03 05:01 UTC, patricia-martinez-imatia commented on templates/list/01-list/README.md
> +<li>Configure routing in `main-routing.module.ts`</li>
lo mismo, los markdown no se renderiza

2024-07-03 05:01 UTC, patricia-martinez-imatia commented on templates/list/01-list/README.md
> +<li>Check if the name of the ATTR, entities and services are concording with your application</li>
Como se ven los <li> sin espaciados en el template manager? Revisarlo porque asi igual queda muy pegado

2024-07-03 05:01 UTC, patricia-martinez-imatia commented on templates/list/01-list/README.md
> +<li>To configure the theme on the login component it is necessary to include `list-home.theme.scss` in `app.scss`</li>
NO es UN COMPONENTE DE LOGIN

2024-07-03 05:01 UTC, patricia-martinez-imatia commented on templates/list/01-list/list/list/list-home.component.scss
> +      max-height: 100%;
Sustituir esta clase por las directivas de flex-layout

2024-07-03 05:01 UTC, patricia-martinez-imatia commented on templates/list/01-list/list/list/list-home.component.scss
> +      .fill-remaining {
Sustituir esta clases  por las directivas de flex-layout

2024-07-03 05:01 UTC, patricia-martinez-imatia commented on templates/list/01-list/list/list/list-home.component.scss
> +        .list-accounts {
Sustituir esta clases  por las directivas de flex-layout

2024-07-03 05:01 UTC, patricia-martinez-imatia commented on templates/list/01-list/list/list/list-home.component.scss
> +            max-height: 100%;
Sustituir esta clases  por las directivas de flex-layout

2024-07-03 05:03 UTC, patricia-martinez-imatia requested changes
Seria util enlaces a la doc al filterbuilder y la lista

2024-07-11 07:51 UTC, patricia-martinez-imatia requested changes

2024-07-11 07:51 UTC, patricia-martinez-imatia commented on templates/list/01-list/README.md
> +2. Check if all the fields that have `@` on it's prefix and sufix are concording to your application data
```suggestion
2. Check if all the fields that have `@` on it's prefix and suffix are concording to your application data
```

2024-07-11 07:51 UTC, patricia-martinez-imatia commented on templates/list/01-list/README.md
> +* **List component** https://ontimizeweb.github.io/docs/v15/components/data/list/overview
```suggestion
* **List component** https://ontimizeweb.github.io/docs/v15/components/data/list/overview
* ** MediaMatcher** https://material.angular.io/cdk/layout/overview
```

2024-07-11 07:51 UTC, patricia-martinez-imatia commented on templates/list/01-list/README.md
> +6. Add the module declaration in the `main.module.ts` file
Point 6 is not necessary

2024-07-11 07:51 UTC, patricia-martinez-imatia commented on templates/list/01-list/README.md
> +7. To configure the theme on the list component it is necessary to include `list-home.theme.scss` in `app.scss`
```suggestion
7. To configure the theme on the list component it is necessary to include `list.theme.scss` in `app.scss`
```

2024-07-11 07:51 UTC, patricia-martinez-imatia commented on templates/list/01-list/README.md
> ++ @import '../../app/list/list-home.theme.scss';
```suggestion
+ @import '../../app/list/list.theme.scss';
```

2024-07-12 08:04 UTC, patricia-martinez-imatia requested changes

2024-07-12 08:04 UTC, patricia-martinez-imatia commented on templates/list/01-list/README.md
> +2. Configure the `o-grid`, you must to modify the values ​​between `@` for the inputs `attr`, `service`, `entity`, `columns`, `quick-filter-columns`, `sort-columns`, `keys` . For more information con
```suggestion
2. Configure the `o-list`, you must to modify the values ​​between `@` for the inputs `attr`, `service`, `entity`, `columns` and `keys` . For more information consult the following url https://ontimizeweb.github.io/docs/v15/components/data/list/overview
```

2024-07-12 08:04 UTC, patricia-martinez-imatia commented on templates/list/01-list/README.md
> +Also you need to configure your `createFilter` method located in the `grid-home.component.ts` file according the filter you want to build. Link to the filter builder documentation at the end of the r
```suggestion
Also you need to configure your `createFilter` method located in the `list-home.component.ts` file according the filter you want to build. Link to the filter builder documentation at the end of the readme.
```

2024-07-12 08:04 UTC, patricia-martinez-imatia commented on templates/list/01-list/README.md
> +Also you need to configure your `createFilter` method located in the `grid-home.component.ts` file according the filter you want to build. Link to the filter builder documentation at the end of the r
Creo que quedaria mejor el link a continuación para seguir el flujo de lectura porque si vas al final del readme luego tienes que volver a buscar el punto el que estabas

2024-07-12 08:04 UTC, patricia-martinez-imatia commented on templates/list/01-list/README.md
> + <o-list #listAccount service="@branches@" entity="@account@" keys="@ACCOUNTID@"
```suggestion
 <o-list #@attr@ service="@branches@" entity="@account@" keys="@ACCOUNTID@"
```

2024-07-12 08:04 UTC, patricia-martinez-imatia commented on templates/list/01-list/README.md
> +3. Configure your filter component setting your inputs and custom ATTR to build the filter. Link to the filter builder documentation at the end of the readme.
```suggestion
3. Configure your `o-filter-builder` setting your inputs and custom ATTR to build the filter. Link to the filter builder documentation at the end of the readme.
```

2024-07-12 08:04 UTC, patricia-martinez-imatia commented on templates/list/01-list/README.md
> +3. Configure your filter component setting your inputs and custom ATTR to build the filter. Link to the filter builder documentation at the end of the readme.
Creo que quedaria mejor el link a continuación para seguir el flujo de lectura porque si vas al final del readme luego tienes que volver a buscar el punto el que estabas

2024-07-12 08:04 UTC, patricia-martinez-imatia commented on templates/list/01-list/list/list-home/list-home.component.ts
> +import { OReportStoreService } from 'ontimize-web-ngx-report';
```suggestion

```

2024-09-17 08:06 UTC, patricia-martinez-imatia commented on templates/list/01-list/README.md
> +Don't forget to customize your `o-list-item` as you want. In this template we are using a `mat-card` component but it isn't necesary.
```suggestion
Don't forget to customize your `o-list-item` as you want. In this template we are using a `mat-card` component but it isn't necessary.
```

2024-09-18 05:06 UTC, patricia-martinez-imatia approved these changes

2024-10-10 08:20 UTC, daniel-grana approved these changes

2024-10-10 08:21 UTC, merged