Grid template 01 created
OntimizeWeb/ontimize-web-templates pull request #14
Opened 2024-07-09 07:27 UTC by javier-fernandez-imatia

2024-07-11 08:08 UTC, patricia-martinez-imatia requested changes

2024-07-11 08:08 UTC, patricia-martinez-imatia commented on templates/grid/README.md
> +2. Check if all the fields that have `@` on it's prefix and sufix are concording to your application data
```suggestion
2. Configure the `o-grid`, you must to modify the values ​​between `@` for the inputs `attr`, `service`, `entity`, `columns`, `quick-filter-columns`, `sort-columns`, `keys` . For more information consult the following url https://ontimizeweb.github.io/docs/v15/components/data/grid/overview
```

2024-09-18 05:09 UTC, patricia-martinez-imatia approved these changes

2024-10-10 08:20 UTC, daniel-grana approved these changes

2024-10-10 08:21 UTC, merged