Login page 01 created
OntimizeWeb/ontimize-web-templates pull request #4
Opened 2024-06-14 12:29 UTC by javier-fernandez-imatia

2024-06-27 06:34 UTC, daniel-grana approved these changes

2024-06-27 06:39 UTC, daniel-grana requested changes

2024-06-27 06:39 UTC, daniel-grana commented on templates/login/01-login/login/login.component.ts
> +      this.dialogService.error("Missing username", "First enter your username");
Utilicemos el servicio de traducciones

2024-07-08 16:03 UTC, daniel-grana submitted a review, later dismissed

2024-07-09 08:22 UTC, daniel-grana submitted a review, later dismissed

2024-07-09 11:21 UTC, patricia-martinez-imatia approved these changes, later dismissed

2024-07-12 08:21 UTC, daniel-grana approved these changes

2024-07-12 09:03 UTC, patricia-martinez-imatia approved these changes

2024-07-12 09:05 UTC, merged