Login page 03 created
OntimizeWeb/ontimize-web-templates pull request #6
Opened 2024-06-17 12:58 UTC by javier-fernandez-imatia

2024-06-27 06:38 UTC, daniel-grana requested changes

2024-06-27 06:38 UTC, daniel-grana commented on templates/login/03-login/login/login.component.ts
> +        this.dialogService.error("Missing username", "First enter your username");
Utilicemos el servicio de traducciones por favor

2024-06-27 13:30 UTC, patricia-martinez-imatia requested changes
Las 4 pantallas  tienen codigo duplicado, creo que quedaria mejor si se refactorizara

2024-06-27 13:30 UTC, patricia-martinez-imatia commented on templates/login/03-login/README.md
> +# LOGIN
```suggestion
```

I think it isnot necessart

2024-06-27 13:30 UTC, patricia-martinez-imatia commented on templates/login/03-login/login/forgot-pass-email/forgot-pass-email.component.ts
> +    } else {
```suggestion
    } 
```

2024-06-27 13:30 UTC, patricia-martinez-imatia commented on templates/login/03-login/login/forgot-pass-email/forgot-pass-email.component.ts
> +    }
```suggestion
```

2024-06-27 13:30 UTC, patricia-martinez-imatia commented on templates/login/03-login/login/forgot-pass-email/forgot-pass-email.component.html
> +                  bad email
Añadir al bundle, el mensaje creo que quedaria mejor FORM_VALIDATION.EMAIL_FORMAT

2024-07-01 06:16 UTC, patricia-martinez-imatia requested changes
![image](https://github.com/OntimizeWeb/ontimize-web-templates/assets/32088627/02575c88-7e2e-467c-9c22-ea648ccad537)

2024-07-03 06:54 UTC, daniel-grana requested changes

2024-07-03 06:54 UTC, daniel-grana commented on templates/login/03-login/login/forgot-pass-email/forgot-pass-email.component.ts
> +      console.log("email valid");
En vez de poner un console.log(), pongamos un comentario explicando que aquí se tiene que hacer la llamada al backend para que se envíe el email con la nueva contraseña.

2024-07-09 08:23 UTC, daniel-grana approved these changes, later dismissed

2024-07-12 08:21 UTC, daniel-grana approved these changes

2024-07-12 09:03 UTC, patricia-martinez-imatia approved these changes

2024-07-12 09:05 UTC, merged