Login page 05 created
OntimizeWeb/ontimize-web-templates pull request #8
Opened 2024-06-20 10:06 UTC by javier-fernandez-imatia

2024-07-03 05:15 UTC, patricia-martinez-imatia requested changes

2024-07-03 05:15 UTC, patricia-martinez-imatia commented on templates/login/05-login/README.md
> +<li>Download and put `login` folder in `src/app/`, `images` into `assets/images/`   </li>
los markdown no funcionan en los li, habria que revisar todos los readme

2024-07-03 05:15 UTC, patricia-martinez-imatia commented on templates/login/05-login/README.md
> +## LEARN MORE
Creo que seria util añadir enlace a la documentacion de OTranslateService

2024-07-03 05:15 UTC, patricia-martinez-imatia commented on templates/login/05-login/login/login.component.html
> +        <div (click)="changeLang('es')" class="language" [ngClass]="{'selected' : isSpanish}">Castellano</div>
el click en el div dara fallo en sonar, revisar los demas ejemplos

2024-07-03 05:15 UTC, patricia-martinez-imatia commented on templates/login/05-login/login/login.component.ts
> +  userCtrl: UntypedFormControl = new UntypedFormControl('', Validators.required);
Creo que se podria usar el tipo adecuado y no UntypedFormGroup

2024-07-03 05:15 UTC, patricia-martinez-imatia commented on templates/login/05-login/login/register/register.component.ts
> +      if (password1 == password2) {
No seria mejor usar la condicion contraria  para no tener el bloque vacio?
```
      if (password1 !== password2) {
```

2024-07-09 08:24 UTC, daniel-grana submitted a review, later dismissed

2024-07-12 08:22 UTC, daniel-grana approved these changes

2024-07-12 08:57 UTC, patricia-martinez-imatia approved these changes

2024-07-12 09:05 UTC, merged